config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post 'results' => 'home#results'

  get 'test' => 'home#test'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def results
  	# params coming the form in the index page
    # capitalization (or lack thereof) shouldn't be a problem
    @food = params[:food]
    @location = params[:location]

    # the client search set up by the Yelp gem
    # takes only two arguments, so if I want to
    # pass more, I can include them in a hash
    parameters = { term: @food, limit: 9 }

    # using the Yelp gem to make the API call
    # the two arguments passed are the location I
    # want to search for, and then the extra parameters
    @results = Yelp.client.search(@location, parameters)
  end

  def test
  	# just testing things out - with hardcoded params
    parameters = { term: "nachos", limit: 10 }

    @results = Yelp.client.search('Atlanta, GA', parameters)

    # printing out to the server to test out other
    # method calls on the API results
    puts "****************"
    puts @results.region.center.latitude
    puts @results.region.center.longitude
    puts "****************"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well mtop-50">
      <h1 class="center-it">What Are You Hungry For?</h1>
      <%= form_tag results_path do %>
        <div class="form-group">
          <%= text_field_tag :food, nil, placeholder: "What Are You In Mood For?", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= text_field_tag :location, nil, placeholder: "City, State", class: "form-control" %>
        </div>
        <div class="form-group center-it">
          <%= submit_tag "Let's Eat", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/results.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well center-it">
      <h2>Let's Get Some <%= @food.capitalize %> in <%= @location %></h2>
    </div>
  </div>
</div>
<div class="row">
  <% @results.businesses.each do |biz| %>
    <div class="col-md-4">
      <div class="well center-it">
        <h3><%= biz.name %></h3>
        <p>
          <%= image_tag biz.rating_img_url_large, alt: "Yelp Rating" %>
        </p>
        <p>
          <% biz.location.display_address.each do |add_line| %>
            <%= add_line %><br />
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/home/test.html.erb
<h1>Test Page</h1>

<div>
	<% @results.businesses.each do |business| %>
		<ul>
			<li><%= business.name %></li>
			<li><%= business.rating %></li>
		</ul>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>